# Swapfile is needed if VM ram is below 2 GiB because DNF is a bloated, ram-hungry piece of shit.
# https://bugzilla.redhat.com/show_bug.cgi?id=1907030
# TODO: gate this behind a check if the system RAM is >= 2 GiB
- name: Create swapfile
  command: dd if=/dev/zero of=/swapfile bs=1M count=2048
  args:
    creates: /swapfile

- name: Check swapfile inited
  ansible.builtin.shell: file --brief /swapfile | grep --quiet ^Linux\ swap
  register: isi
  failed_when: (isi.rc not in [0,1])
  changed_when: false

- name: Init swapfile
  command: mkswap /swapfile
  when: isi.rc != 0

- name: Check swapfile enabled
  ansible.builtin.shell: swapon | grep --quiet ^/swapfile
  register: ise
  failed_when: (ise.rc not in [0,1])
  changed_when: false

- name: Enable swapfile
  command: swapon /swapfile
  when: ise.rc != 0

- name: Add swapfile to boot mounts
  template: src=swapfile.swap.j2 dest=/etc/systemd/system/swapfile.swap owner=root group=root mode=0644

- name: Enable swapfile systemd unit
  systemd_service:
    daemon_reload: true
    name: swapfile.swap
    enabled: yes

- name: Activate EPEL
  ansible.builtin.dnf: name=epel-release state=present install_weak_deps=False
  register: _aep_out
- name: Results
  when: _aep_out.changed
  ansible.builtin.debug: var=_aep_out.results
- name: Enable CRB repo
  community.general.dnf_config_manager:
    name: crb
    state: enabled

- name: Set SELinux policy
  template: src=selinux-config.j2 dest=/etc/selinux/config owner=root group=root mode=0644
  notify: Reboot host

# There is no need for this cache, as DNF/packages are only being touched during system updates.
- name: Disable DNF makecace
  service: name=dnf-makecache.timer enabled=no state=stopped

# vim: nocindent autoindent ts=2 sts=2 sw=2 expandtab
