- name: Reload tmpfiles
  command: systemd-tmpfiles --create --prefix=/run

- name: Restart spamassassin
  service: name=spamassassin state=restarted

- name: Restart spamass-milter
  service: name=spamass-milter state=restarted

- name: Compile spamassassin rules
  command: sa-compile
