# Pre-installation manual tasks:
# 1. Provision the VM / server
# 2. Install AlmaLinux 9
# 3. Set up root user with SSH key
# 4. Set hostname and proper DNS records to match
# Then you can run this playbook.

- name: Initial installation of wolf.zootboy.com
  hosts: wolf.zootboy.com
  remote_user: root
  vars:
    unbound_take_over_resolv: true
    # The domain name that emails are sent & received from. Doesn't need to be the server's hostname.
    email_domain: wolf.zootboy.com
    # Email address of the responsible sysadmin. Used by mailman.
    site_owner_email_addr: sean@seangreenslade.com
    # Email address that is used as a fallback "From" for things like confirmation emails.
    default_from_email_addr: postmaster@wolf.zootboy.com
  roles:
#  - { role: alma-tweaks  }
#  - { role: common       }
#  - { role: firewall     }
  - { role: postfix      }
#  - { role: sshd         }
#  - { role: unbound      }
#  - { role: spamassassin }
#  - { role: opendkim     }
#  - { role: nginx        }
  - { role: mariadb      }
  - { role: mailman3     }

# General TODOs:
# OS
# - Switch to Alma 10
# firewall
# - Complete port blocking on outgoing connections
# postfix
# - Set up circular buffer mail sampler
# - Copy msa_header_checks from arch
# nginx
# - Get basic server working
# - Automatic LE certs
# - Postorious
# - Hyperkitty
# - Wordpress
# - Mediawiki
# spamassassin
# - Get bayes set up and working
# System-wide
# - Backups of data (e.g. mailing list archives)
# Export/Import
# - Process to export data from old server
# - Playbook to import old data


# vim: ts=2 sts=2 sw=2 expandtab
